apply plugin: 'com.android.application'

android {
    namespace "com.learnx.app"
    compileSdk rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.learnx.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
            ignoreAssetsPattern = '!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:"
    implementation "androidx.coordinatorlayout:coordinatorlayout:"
    implementation "androidx.core:core-splashscreen:"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:"
    androidTestImplementation "androidx.test.ext:junit:"
    androidTestImplementation "androidx.test.espresso:espresso-core:"
}

apply from: 'capacitor.build.gradle'